In [1]:
import pandas as pd

# Load data
train_transaction = pd.read_csv("train_transaction.csv")
train_identity = pd.read_csv("train_identity.csv")

test_transaction = pd.read_csv("test_transaction.csv")
test_identity = pd.read_csv("test_identity.csv")

# Merge on TransactionID
train_df = train_transaction.merge(train_identity, on="TransactionID", how="left")
test_df = test_transaction.merge(test_identity, on="TransactionID", how="left")

# Check shapes
print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

Train shape: (590540, 434)
Test shape: (506691, 433)

In [2]:
train_df.head()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M

In [6]:
# Count missing values per column
null_counts = train_df.isnull().sum()

# Filter only columns with missing values
null_counts = null_counts[null_counts > 0].sort_values(ascending=False)

# Show top 20 columns with most missing values
print(null_counts.head(25))

# Percentage of missing values
null_percent = (train_df.isnull().sum() / len(train_df)) * 100

# Filter and sort
null_percent = null_percent[null_percent > 0].sort_values(ascending=False)

# Display top 20
print(null_percent.head(25))

id_24    585793
id_25    585408
id_07    585385
id_08    585385
id_21    585381
id_26    585377
id_23    585371
id_22    585371
id_27    585371
dist2    552913
D7       551623
id_18    545427
D13      528588
D14      528353
D12      525823
id_04    524216
id_03    524216
D6       517353
id_33    517251
id_10    515614
D8       515614
id_09    515614
D9       515614
id_30    512975
id_32    512954
dtype: int64
id_24    99.196159
id_25    99.130965
id_07    99.127070
id_08    99.127070
id_21    99.126393
id_26    99.125715
id_23    99.124699
id_22    99.124699
id_27    99.124699
dist2    93.628374
D7       93.409930
id_18    92.360721
D13      89.509263
D14      89.469469
D12      89.041047
id_04    88.768923
id_03    88.768923
D6       87.606767
id_33    87.589494
id_10    87.312290
D8       87.312290
id_09    87.312290
D9       87.312290
id_30    86.865411
id_32    86.861855
dtype: float64

In [9]:
# Calculate % of missing values
null_percent = (train_df.isnull().sum() / len(train_df)) * 100

# Get list of columns with > 80% missing
cols_to_drop = null_percent[null_percent > 80].index

print("Columns to drop:", len(cols_to_drop))
print(cols_to_drop)

# Drop from both train and test
train_df.drop(cols_to_drop, axis=1, inplace=True)

print("Train shape after drop:", train_df.shape)

Columns to drop: 0
Index([], dtype='object')
Train shape after drop: (590540, 360)

In [10]:
df = train_df.copy()
df.head()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,id_20,id_28,id_29,id_31,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,144.0,New,NotFound,samsung browser 6.2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M

In [11]:
# Check number of columns by dtype
print("Object (categorical) columns:", df.select_dtypes(include=['object']).shape[1])
print("Integer columns:", df.select_dtypes(include=['int64']).shape[1])
print("Float columns:", df.select_dtypes(include=['float64']).shape[1])

Object (categorical) columns: 26
Integer columns: 4
Float columns: 330

In [13]:
# Separate numeric and categorical columns
num_cols = df.select_dtypes(include=["int64", "float64"]).columns
cat_cols = df.select_dtypes(include=["object"]).columns

# Numeric NaNs â†’ median
for col in num_cols:
    median_val = df[col].median()
    df[col] = df[col].fillna(median_val)

# Categorical NaNs â†’ mode
for col in cat_cols:
    mode_val = df[col].mode()[0] if not df[col].mode().empty else "missing"
    df[col] = df[col].fillna(mode_val)


'''# Fill numeric NaNs with median
for col in num_cols:
    median_val = df[col].median()
    df[col].fillna(median_val, inplace=True)

# Fill categorical NaNs with mode
for col in cat_cols:
    mode_val = df[col].mode()[0] if not df[col].mode().empty else "missing"
    df[col].fillna(mode_val, inplace=True)'''

'# Fill numeric NaNs with median\nfor col in num_cols:\n    median_val = df[col].median()\n    df[col].fillna(median_val, inplace=True)\n\n# Fill categorical NaNs with mode\nfor col in cat_cols:\n    mode_val = df[col].mode()[0] if not df[col].mode().empty else "missing"\n    df[col].fillna(mode_val, inplace=True)'

In [14]:
# Total number of null values in the whole dataframe
print("Total null values:", df.isnull().sum().sum())

# Number of columns that still contain at least one null
print("Columns with nulls:", (df.isnull().sum() > 0).sum())

# List of columns (if any) that still have nulls, with counts
null_counts = df.isnull().sum()
null_counts = null_counts[null_counts > 0].sort_values(ascending=False)

print(null_counts)

Total null values: 0
Columns with nulls: 0
Series([], dtype: int64)

In [15]:
df.head()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,id_20,id_28,id_29,id_31,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987000,0,86400,68.5,W,13926,361.0,150.0,discover,142.0,...,472.0,Found,Found,chrome 63.0,T,F,T,F,desktop,Windows
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,472.0,Found,Found,chrome 63.0,T,F,T,F,desktop,Windows
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,472.0,Found,Found,chrome 63.0,T,F,T,F,desktop,Windows
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,472.0,Found,Found,chrome 63.0,T,F,T,F,desktop,Windows
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,144.0,New,NotFound,samsung browser 6.2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M

In [17]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Downloading scikit_learn-1.7.1-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.22.0 in c:\users\kptri\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.3.2)
Collecting scipy>=1.8.0 (from scikit-learn)
  Downloading scipy-1.16.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.5.2-py3-none-any.whl.metadata (5.6 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.7.1-cp313-cp313-win_amd64.whl (8.7 MB)
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.7 MB 1.3 MB/s eta 0:00:07
   --- ------------------------------------ 0.8/8.7 MB 1.3 MB/s eta 0:00:07
   ---- ----------------------------------- 1.0/8.7 MB 1.3 MB/s eta 0:00:07
   ------ --------------------------------- 1.3/8.7 MB 1.3 MB/s eta 0:00:06
   ------- -------------------------------- 1.6/8.7 MB 1.3 MB/s eta 0:00:06
   -------- ------------------------------- 1.8/8.7 MB 1.3 MB/s eta 0:00:06
   --------- ------------------------------ 2.1/8.7 MB 1.3 MB/s eta 0:00:06
   ---------- ----------------------------- 2.4/8.7 MB 1.3 MB/s eta 0:00:05
   ------------ --------------------------- 2.6/8.7 MB 1.3 MB/s eta 0:00:05
   ------------- -------------------------- 2.9/8.7 MB 1.3 MB/s eta 0:00:05
   -------------- ------------------------- 3.1/8.7 MB 1.3 MB/s eta 0:00:05
   --------------- ------------------------ 3.4/8.7 MB 1.3 MB/s eta 0:00:05
   ---------------- ----------------------- 3.7/8.7 MB 1.3 MB/s eta 0:00:04
   ------------------ --------------------- 3.9/8.7 MB 1.3 MB/s eta 0:00:04
   ------------------- -------------------- 4.2/8.7 MB 1.3 MB/s eta 0:00:04
   -------------------- ------------------- 4.5/8.7 MB 1.3 MB/s eta 0:00:04
   --------------------- ------------------ 4.7/8.7 MB 1.3 MB/s eta 0:00:04
   ---------------------- ----------------- 5.0/8.7 MB 1.3 MB/s eta 0:00:03
   ------------------------ --------------- 5.2/8.7 MB 1.3 MB/s eta 0:00:03
   ------------------------- -------------- 5.5/8.7 MB 1.3 MB/s eta 0:00:03
   -------------------------- ------------- 5.8/8.7 MB 1.3 MB/s eta 0:00:03
   --------------------------- ------------ 6.0/8.7 MB 1.3 MB/s eta 0:00:03
   ---------------------------- ----------- 6.3/8.7 MB 1.3 MB/s eta 0:00:02
   ------------------------------ --------- 6.6/8.7 MB 1.3 MB/s eta 0:00:02
   ------------------------------- -------- 6.8/8.7 MB 1.3 MB/s eta 0:00:02
   -------------------------------- ------- 7.1/8.7 MB 1.3 MB/s eta 0:00:02
   --------------------------------- ------ 7.3/8.7 MB 1.3 MB/s eta 0:00:02
   ---------------------------------- ----- 7.6/8.7 MB 1.3 MB/s eta 0:00:01
   ------------------------------------ --- 7.9/8.7 MB 1.3 MB/s eta 0:00:01
   ------------------------------------- -- 8.1/8.7 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 8.4/8.7 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 8.7/8.7 MB 1.3 MB/s  0:00:06
Downloading joblib-1.5.2-py3-none-any.whl (308 kB)
Downloading scipy-1.16.1-cp313-cp313-win_amd64.whl (38.5 MB)
   ---------------------------------------- 0.0/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/38.5 MB ? eta -:--:--
    --------------------------------------- 0.8/38.5 MB 1.3 MB/s eta 0:00:30
   - -------------------------------------- 1.0/38.5 MB 1.3 MB/s eta 0:00:29
   - -------------------------------------- 1.3/38.5 MB 1.3 MB/s eta 0:00:29
   - -------------------------------------- 1.6/38.5 MB 1.3 MB/s eta 0:00:29
   - -------------------------------------- 1.8/38.5 MB 1.3 MB/s eta 0:00:29
   -- ------------------------------------- 2.1/38.5 MB 1.3 MB/s eta 0:00:28
   -- ------------------------------------- 2.4/38.5 MB 1.3 MB/s eta 0:00:28
   -- ------------------------------------- 2.6/38.5 MB 1.3 MB/s eta 0:00:28
   -- ------------------------------------- 2.9/38.5 MB 1.3 MB/s eta 0:00:28
   --- ------------------------------------ 3.1/38.5 MB 1.3 MB/s eta 0:00:28
   --- ------------------------------------ 3.4/38.5 MB 1.3 MB/s eta 0:00:28
   --- ------------------------------------ 3.7/38.5 MB 1.3 MB/s eta 0:00:27
   ---- ----------------------------------- 3.9/38.5 MB 1.3 MB/s eta 0:00:27
   ---- ----------------------------------- 4.2/38.5 MB 1.3 MB/s eta 0:00:27
   ---- ----------------------------------- 4.5/38.5 MB 1.3 MB/s eta 0:00:27
   ---- ----------------------------------- 4.7/38.5 MB 1.3 MB/s eta 0:00:27
   ----- ---------------------------------- 5.0/38.5 MB 1.3 MB/s eta 0:00:26
   ----- ---------------------------------- 5.2/38.5 MB 1.3 MB/s eta 0:00:26
   ----- ---------------------------------- 5.5/38.5 MB 1.3 MB/s eta 0:00:26
   ----- ---------------------------------- 5.8/38.5 MB 1.3 MB/s eta 0:00:26
   ------ --------------------------------- 6.0/38.5 MB 1.3 MB/s eta 0:00:26
   ------ --------------------------------- 6.3/38.5 MB 1.3 MB/s eta 0:00:25
   ------ --------------------------------- 6.6/38.5 MB 1.3 MB/s eta 0:00:25
   ------- -------------------------------- 6.8/38.5 MB 1.3 MB/s eta 0:00:25
   ------- -------------------------------- 7.1/38.5 MB 1.3 MB/s eta 0:00:25
   ------- -------------------------------- 7.3/38.5 MB 1.3 MB/s eta 0:00:25
   ------- -------------------------------- 7.6/38.5 MB 1.3 MB/s eta 0:00:24
   -------- ------------------------------- 7.9/38.5 MB 1.3 MB/s eta 0:00:24
   -------- ------------------------------- 8.1/38.5 MB 1.3 MB/s eta 0:00:24
   -------- ------------------------------- 8.4/38.5 MB 1.3 MB/s eta 0:00:24
   -------- ------------------------------- 8.7/38.5 MB 1.3 MB/s eta 0:00:24
   --------- ------------------------------ 8.9/38.5 MB 1.3 MB/s eta 0:00:23
   --------- ------------------------------ 9.2/38.5 MB 1.3 MB/s eta 0:00:23
   ---------- ----------------------------- 9.7/38.5 MB 1.3 MB/s eta 0:00:23
   ---------- ----------------------------- 10.0/38.5 MB 1.3 MB/s eta 0:00:23
   ---------- ----------------------------- 10.2/38.5 MB 1.3 MB/s eta 0:00:22
   ---------- ----------------------------- 10.5/38.5 MB 1.3 MB/s eta 0:00:22
   ----------- ---------------------------- 10.7/38.5 MB 1.3 MB/s eta 0:00:22
   ----------- ---------------------------- 11.0/38.5 MB 1.3 MB/s eta 0:00:22
   ----------- ---------------------------- 11.3/38.5 MB 1.3 MB/s eta 0:00:22
   ----------- ---------------------------- 11.5/38.5 MB 1.3 MB/s eta 0:00:21
   ------------ --------------------------- 11.8/38.5 MB 1.3 MB/s eta 0:00:21
   ------------ --------------------------- 12.1/38.5 MB 1.3 MB/s eta 0:00:21
   ------------ --------------------------- 12.3/38.5 MB 1.3 MB/s eta 0:00:21
   ------------- -------------------------- 12.6/38.5 MB 1.3 MB/s eta 0:00:21
   ------------- -------------------------- 12.8/38.5 MB 1.3 MB/s eta 0:00:20
   ------------- -------------------------- 13.1/38.5 MB 1.3 MB/s eta 0:00:20
   ------------- -------------------------- 13.4/38.5 MB 1.3 MB/s eta 0:00:20
   -------------- ------------------------- 13.6/38.5 MB 1.3 MB/s eta 0:00:20
   -------------- ------------------------- 13.9/38.5 MB 1.3 MB/s eta 0:00:20
   -------------- ------------------------- 14.2/38.5 MB 1.3 MB/s eta 0:00:19
   -------------- ------------------------- 14.4/38.5 MB 1.3 MB/s eta 0:00:19
   --------------- ------------------------ 14.7/38.5 MB 1.3 MB/s eta 0:00:19
   --------------- ------------------------ 14.9/38.5 MB 1.3 MB/s eta 0:00:19
   --------------- ------------------------ 15.2/38.5 MB 1.3 MB/s eta 0:00:19
   ---------------- ----------------------- 15.5/38.5 MB 1.3 MB/s eta 0:00:18
   ---------------- ----------------------- 15.7/38.5 MB 1.3 MB/s eta 0:00:18
   ---------------- ----------------------- 16.0/38.5 MB 1.3 MB/s eta 0:00:18
   ---------------- ----------------------- 16.3/38.5 MB 1.3 MB/s eta 0:00:18
   ----------------- ---------------------- 16.5/38.5 MB 1.3 MB/s eta 0:00:18
   ----------------- ---------------------- 16.8/38.5 MB 1.3 MB/s eta 0:00:17
   ----------------- ---------------------- 17.0/38.5 MB 1.3 MB/s eta 0:00:17
   ----------------- ---------------------- 17.3/38.5 MB 1.3 MB/s eta 0:00:17
   ------------------ --------------------- 17.6/38.5 MB 1.3 MB/s eta 0:00:17
   ------------------ --------------------- 17.8/38.5 MB 1.3 MB/s eta 0:00:17
   ------------------ --------------------- 18.1/38.5 MB 1.3 MB/s eta 0:00:16
   ------------------- -------------------- 18.4/38.5 MB 1.3 MB/s eta 0:00:16
   ------------------- -------------------- 18.6/38.5 MB 1.3 MB/s eta 0:00:16
   ------------------- -------------------- 18.9/38.5 MB 1.3 MB/s eta 0:00:16
   ------------------- -------------------- 19.1/38.5 MB 1.3 MB/s eta 0:00:16
   -------------------- ------------------- 19.4/38.5 MB 1.3 MB/s eta 0:00:15
   -------------------- ------------------- 19.7/38.5 MB 1.3 MB/s eta 0:00:15
   -------------------- ------------------- 19.9/38.5 MB 1.3 MB/s eta 0:00:15
   -------------------- ------------------- 20.2/38.5 MB 1.3 MB/s eta 0:00:15
   --------------------- ------------------ 20.4/38.5 MB 1.3 MB/s eta 0:00:15
   --------------------- ------------------ 20.7/38.5 MB 1.3 MB/s eta 0:00:14
   --------------------- ------------------ 21.0/38.5 MB 1.3 MB/s eta 0:00:14
   ---------------------- ----------------- 21.2/38.5 MB 1.3 MB/s eta 0:00:14
   ---------------------- ----------------- 21.5/38.5 MB 1.3 MB/s eta 0:00:14
   ---------------------- ----------------- 21.8/38.5 MB 1.3 MB/s eta 0:00:14
   ---------------------- ----------------- 22.0/38.5 MB 1.3 MB/s eta 0:00:13
   ----------------------- ---------------- 22.3/38.5 MB 1.3 MB/s eta 0:00:13
   ----------------------- ---------------- 22.5/38.5 MB 1.3 MB/s eta 0:00:13
   ----------------------- ---------------- 22.8/38.5 MB 1.3 MB/s eta 0:00:13
   ----------------------- ---------------- 23.1/38.5 MB 1.3 MB/s eta 0:00:12
   ------------------------ --------------- 23.3/38.5 MB 1.3 MB/s eta 0:00:12
   ------------------------ --------------- 23.6/38.5 MB 1.3 MB/s eta 0:00:12
   ------------------------ --------------- 23.9/38.5 MB 1.3 MB/s eta 0:00:12
   ------------------------- -------------- 24.1/38.5 MB 1.3 MB/s eta 0:00:12
   ------------------------- -------------- 24.4/38.5 MB 1.3 MB/s eta 0:00:11
   ------------------------- -------------- 24.6/38.5 MB 1.3 MB/s eta 0:00:11
   ------------------------- -------------- 24.9/38.5 MB 1.3 MB/s eta 0:00:11
   -------------------------- ------------- 25.2/38.5 MB 1.3 MB/s eta 0:00:11
   -------------------------- ------------- 25.4/38.5 MB 1.3 MB/s eta 0:00:11
   -------------------------- ------------- 25.7/38.5 MB 1.3 MB/s eta 0:00:10
   -------------------------- ------------- 26.0/38.5 MB 1.3 MB/s eta 0:00:10
   --------------------------- ------------ 26.2/38.5 MB 1.3 MB/s eta 0:00:10
   --------------------------- ------------ 26.5/38.5 MB 1.3 MB/s eta 0:00:10
   --------------------------- ------------ 26.7/38.5 MB 1.3 MB/s eta 0:00:10
   ---------------------------- ----------- 27.0/38.5 MB 1.3 MB/s eta 0:00:09
   ---------------------------- ----------- 27.5/38.5 MB 1.3 MB/s eta 0:00:09
   ---------------------------- ----------- 27.8/38.5 MB 1.3 MB/s eta 0:00:09
   ----------------------------- ---------- 28.0/38.5 MB 1.3 MB/s eta 0:00:09
   ----------------------------- ---------- 28.3/38.5 MB 1.3 MB/s eta 0:00:08
   ----------------------------- ---------- 28.6/38.5 MB 1.3 MB/s eta 0:00:08
   ----------------------------- ---------- 28.8/38.5 MB 1.3 MB/s eta 0:00:08
   ------------------------------ --------- 29.1/38.5 MB 1.3 MB/s eta 0:00:08
   ------------------------------ --------- 29.4/38.5 MB 1.3 MB/s eta 0:00:08
   ------------------------------ --------- 29.6/38.5 MB 1.3 MB/s eta 0:00:07
   ------------------------------- -------- 29.9/38.5 MB 1.3 MB/s eta 0:00:07
   ------------------------------- -------- 30.1/38.5 MB 1.3 MB/s eta 0:00:07
   ------------------------------- -------- 30.4/38.5 MB 1.3 MB/s eta 0:00:07
   ------------------------------- -------- 30.7/38.5 MB 1.3 MB/s eta 0:00:07
   -------------------------------- ------- 30.9/38.5 MB 1.3 MB/s eta 0:00:06
   -------------------------------- ------- 31.2/38.5 MB 1.3 MB/s eta 0:00:06
   -------------------------------- ------- 31.5/38.5 MB 1.3 MB/s eta 0:00:06
   -------------------------------- ------- 31.7/38.5 MB 1.3 MB/s eta 0:00:06
   --------------------------------- ------ 32.0/38.5 MB 1.3 MB/s eta 0:00:06
   --------------------------------- ------ 32.2/38.5 MB 1.3 MB/s eta 0:00:05
   --------------------------------- ------ 32.5/38.5 MB 1.3 MB/s eta 0:00:05
   ---------------------------------- ----- 32.8/38.5 MB 1.3 MB/s eta 0:00:05
   ---------------------------------- ----- 33.0/38.5 MB 1.3 MB/s eta 0:00:05
   ---------------------------------- ----- 33.3/38.5 MB 1.3 MB/s eta 0:00:05
   ---------------------------------- ----- 33.6/38.5 MB 1.3 MB/s eta 0:00:04
   ----------------------------------- ---- 33.8/38.5 MB 1.3 MB/s eta 0:00:04
   ----------------------------------- ---- 34.1/38.5 MB 1.3 MB/s eta 0:00:04
   ----------------------------------- ---- 34.3/38.5 MB 1.3 MB/s eta 0:00:04
   ----------------------------------- ---- 34.6/38.5 MB 1.3 MB/s eta 0:00:04
   ------------------------------------ --- 34.9/38.5 MB 1.3 MB/s eta 0:00:03
   ------------------------------------ --- 35.1/38.5 MB 1.3 MB/s eta 0:00:03
   ------------------------------------ --- 35.4/38.5 MB 1.3 MB/s eta 0:00:03
   ------------------------------------- -- 35.7/38.5 MB 1.3 MB/s eta 0:00:03
   ------------------------------------- -- 35.9/38.5 MB 1.3 MB/s eta 0:00:02
   ------------------------------------- -- 36.2/38.5 MB 1.3 MB/s eta 0:00:02
   ------------------------------------- -- 36.4/38.5 MB 1.3 MB/s eta 0:00:02
   -------------------------------------- - 36.7/38.5 MB 1.3 MB/s eta 0:00:02
   -------------------------------------- - 37.0/38.5 MB 1.3 MB/s eta 0:00:02
   -------------------------------------- - 37.2/38.5 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 37.5/38.5 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  37.7/38.5 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  38.0/38.5 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  38.3/38.5 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 38.5/38.5 MB 1.3 MB/s  0:00:29
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]

In [18]:
from sklearn.preprocessing import LabelEncoder

for col in cat_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

In [19]:
print(df.dtypes.value_counts())

float64    330
int64       30
Name: count, dtype: int64

In [21]:
df.shape

(590540, 360)

In [22]:
df.to_csv("my_cleaned_data.csv", index=False)

In [23]:
df.head()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,id_20,id_28,id_29,id_31,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987000,0,86400,68.5,4,13926,361.0,150.0,1,142.0,...,472.0,0,0,47,1,0,1,0,0,1598
1,2987001,0,86401,29.0,4,2755,404.0,150.0,2,102.0,...,472.0,0,0,47,1,0,1,0,0,1598
2,2987002,0,86469,59.0,4,4663,490.0,150.0,3,166.0,...,472.0,0,0,47,1,0,1,0,0,1598
3,2987003,0,86499,50.0,4,18132,567.0,150.0,2,117.0,...,472.0,0,0,47,1,0,1,0,0,1598
4,2987004,0,86506,50.0,1,4497,514.0,150.0,2,102.0,...,144.0,1,1,123,1,0,1,1,1,954

In [24]:
df2 = df.copy()

In [25]:
df2.head()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,id_20,id_28,id_29,id_31,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987000,0,86400,68.5,4,13926,361.0,150.0,1,142.0,...,472.0,0,0,47,1,0,1,0,0,1598
1,2987001,0,86401,29.0,4,2755,404.0,150.0,2,102.0,...,472.0,0,0,47,1,0,1,0,0,1598
2,2987002,0,86469,59.0,4,4663,490.0,150.0,3,166.0,...,472.0,0,0,47,1,0,1,0,0,1598
3,2987003,0,86499,50.0,4,18132,567.0,150.0,2,117.0,...,472.0,0,0,47,1,0,1,0,0,1598
4,2987004,0,86506,50.0,1,4497,514.0,150.0,2,102.0,...,144.0,1,1,123,1,0,1,1,1,954

In [27]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

# Features and target
X = df2.drop("isFraud", axis=1)
y = df2["isFraud"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Train Random Forest
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

# Get feature importance values
importances = rf.feature_importances_

# Put into DataFrame
importance_df = pd.DataFrame({
    "feature": X.columns,
    "importance": importances
}).sort_values(by="importance", ascending=False)

In [41]:
print(importance_df.head(20))

            feature  importance
1     TransactionDT    0.031105
0     TransactionID    0.030433
2    TransactionAmt    0.025951
4             card1    0.025268
5             card2    0.020953
27              C13    0.018802
15               C1    0.018543
10            addr1    0.018522
217            V201    0.014945
28              C14    0.012459
13    P_emaildomain    0.012111
8             card5    0.011767
274            V258    0.011244
25              C11    0.011115
16               C2    0.010708
205            V189    0.010565
339           id_02    0.010335
36              D15    0.010241
20               C6    0.009539
273            V257    0.009538

In [42]:
df2 = df2.drop("TransactionID", axis=1)

In [43]:
df2.to_csv("CleanedData.csv", index=False)

In [44]:
df2.head()

,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,id_20,id_28,id_29,id_31,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,0,86400,68.5,4,13926,361.0,150.0,1,142.0,1,...,472.0,0,0,47,1,0,1,0,0,1598
1,0,86401,29.0,4,2755,404.0,150.0,2,102.0,1,...,472.0,0,0,47,1,0,1,0,0,1598
2,0,86469,59.0,4,4663,490.0,150.0,3,166.0,2,...,472.0,0,0,47,1,0,1,0,0,1598
3,0,86499,50.0,4,18132,567.0,150.0,2,117.0,2,...,472.0,0,0,47,1,0,1,0,0,1598
4,0,86506,50.0,1,4497,514.0,150.0,2,102.0,1,...,144.0,1,1,123,1,0,1,1,1,954

In [45]:
df3 = df2.copy()
df3.head()

,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,id_20,id_28,id_29,id_31,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,0,86400,68.5,4,13926,361.0,150.0,1,142.0,1,...,472.0,0,0,47,1,0,1,0,0,1598
1,0,86401,29.0,4,2755,404.0,150.0,2,102.0,1,...,472.0,0,0,47,1,0,1,0,0,1598
2,0,86469,59.0,4,4663,490.0,150.0,3,166.0,2,...,472.0,0,0,47,1,0,1,0,0,1598
3,0,86499,50.0,4,18132,567.0,150.0,2,117.0,2,...,472.0,0,0,47,1,0,1,0,0,1598
4,0,86506,50.0,1,4497,514.0,150.0,2,102.0,1,...,144.0,1,1,123,1,0,1,1,1,954

In [46]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

# Features and target
X = df3.drop("isFraud", axis=1)
y = df3["isFraud"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Train Random Forest
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

# Get feature importance values
importances = rf.feature_importances_

# Put into DataFrame
importance_df = pd.DataFrame({
    "feature": X.columns,
    "importance": importances
}).sort_values(by="importance", ascending=False)

In [47]:
print(importance_df.head(20))

            feature  importance
0     TransactionDT    0.033738
1    TransactionAmt    0.028824
3             card1    0.027476
4             card2    0.022717
9             addr1    0.020618
14               C1    0.018445
26              C13    0.017864
27              C14    0.013803
12    P_emaildomain    0.013204
216            V201    0.013167
7             card5    0.012478
24              C11    0.010953
338           id_02    0.010902
35              D15    0.010539
11            dist1    0.010222
15               C2    0.010036
19               C6    0.010034
25              C12    0.010032
273            V258    0.010003
258            V243    0.009875

In [60]:
importance_df.head(225)

            feature  importance
0     TransactionDT    0.033738
1    TransactionAmt    0.028824
3             card1    0.027476
4             card2    0.022717
9             addr1    0.020618
..              ...         ...
341           id_11    0.001042
326            V311    0.001042
117             V73    0.001025
319            V304    0.001022
99              V55    0.001015

[225 rows x 2 columns]

In [57]:
importance_df.describe()

         importance
count  3.580000e+02
mean   2.793296e-03
std    4.079944e-03
min    4.410773e-11
25%    7.170099e-04
50%    1.384338e-03
75%    3.093335e-03
max    3.373848e-02

In [61]:
top_features = importance_df.head(150)["feature"].tolist()
df2_reduced = df2[top_features + ["isFraud"]]

In [62]:
df2_reduced.head()

,TransactionDT,TransactionAmt,card1,card2,addr1,C1,C13,C14,P_emaildomain,V201,...,V232,V293,V273,M2,V321,V298,V74,V261,V209,isFraud
0,86400,68.5,13926,361.0,315.0,1.0,1.0,1.0,16,1.0,...,0.0,0.0,0.0,1,0.0,0.0,0.0,1.0,0.0,0
1,86401,29.0,2755,404.0,325.0,1.0,1.0,1.0,16,1.0,...,0.0,0.0,0.0,1,0.0,0.0,0.0,1.0,0.0,0
2,86469,59.0,4663,490.0,330.0,1.0,1.0,1.0,35,1.0,...,0.0,0.0,0.0,1,0.0,0.0,0.0,1.0,0.0,0
3,86499,50.0,18132,567.0,476.0,2.0,25.0,1.0,53,1.0,...,0.0,1.0,0.0,1,0.0,0.0,0.0,1.0,0.0,0
4,86506,50.0,4497,514.0,420.0,1.0,1.0,1.0,16,1.0,...,0.0,0.0,0.0,1,0.0,0.0,0.0,1.0,0.0,0

In [66]:
df2_reduced.to_csv("CleanedData150.csv", index = False)

In [64]:
threshold = 0.001
selected_features = importance_df[importance_df["importance"] > threshold]["feature"].tolist()
df2_reducedTh = df2[selected_features + ["isFraud"]]

In [67]:
df2_reducedTh.to_csv("CleanedDataTh.csv", index = False)